### PR TITLE
Add heading-anchor extension

### PR DESCRIPTION
**Pull request by mcruzdev**
This pull request adds support for heading anchor!

It is a great feature for feature features, like searching...

### CODE REVIEW

**Comment by mkouba** [comment]
Does it make sense to introduce a new extension for this functionality? It could be a functionality of the core `markdown` extension, probably guarded by a config flag...

**Comment by ia3andy** [comment]
@mkouba I am also not sure about how to deal with those, but since they are runtime dependencies, better split like this IMO

**Comment by mkouba** [comment]
> @mkouba I am also not sure about how to deal with those, but since they are runtime dependencies, better split like this IMO

> > Does it make sense to introduce a new extension for this functionality? It could be a functionality of the core `markdown` extension, probably guarded by a config flag...
> 
> I really prefer this approach for the simplicity, it would be enabled by default.

@mcruzdev @ia3andy I don't think it's reasonable to add a new extension for each major feature. IMO a new extension is adequate if a feature requires a new dependency (another extension or library).

**Comment by ia3andy** [comment]
It requires a new dependency

**Comment by mkouba** [comment]
> It requires a new dependency

Ah, sorry I completely missed the `commonmark-ext-heading-anchor` dependency. So pls ignore my previous comments ;-).

**Pull request merged**
