### PR TITLE
Introduce AsciidoctorJ

### PR DESCRIPTION
**Pull request by ia3andy**
- Add quarkus-qute-web-asciidoctorj extension.
- Leverage asciidoctorj and asciidoctorj-diagram libraries to render asciidoc content.
- This doesn't support native.
- Rename qute-web-asciidoc to qute-web-asciidoc-light

Supersed #144

### CODE REVIEW

**Comment by maxandersen** [comment]
Why the rename to asciidoc-light? Shouldn't it use the name of the library like asciidoc-yupiik-java or something if you want it be different?

**Comment by ia3andy** [comment]
@maxandersen yupiik is not something relevant here as it's a library inside another..

**Comment by ia3andy** [comment]
Closing as we want to add this directly in Roq: https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/roq/near/489999792

**Comment by ia3andy** [comment]
I need to extract the RawString part..

**Pull request closed without merging**
