### PR TITLE
Instanciate parser with a LocalContentResolver

### LINKED ISSUE #138: Asciidoc converter prevent the use of includes
As of now, the converter creates a new instance of parser using `Parser.ParserContext(null)`, that will trigger `NullPointerException` if includes are use, or anything that will require a `ContentResolver`.

Passing the default `ContentResolver` is sufficient, and will at worst trigger understandable exception.

### PR DESCRIPTION
**Pull request by jtama**
Fixes #138

### CODE REVIEW

**Review by ia3andy — APPROVED** [review]
LGTM

**Comment by ia3andy** [comment]
@mkouba I let you merge this patch

**Comment by jtama** [comment]
Thanks to @ia3andy, we have a workaround by using qute includes instead of asciidoc one.

I let you decide wether to close or merge the PR.

**Comment by mkouba** [comment]
I have to admit that I don't have enough context but I agree that we should avoid `NullPointerException`s where possible.

**Pull request merged**
