### PR TITLE
allow qute.html extension for templates

### PR DESCRIPTION
**Pull request by kucharzyk**
This PR will fix issue #70 and allow using qute.html extension for templates

### CODE REVIEW

**Comment by mkouba** [comment]
Hi @kucharzyk and thanks for the PR!

Just to be clear - this PR merely fixed the problem with index pages, right? In other words, `/pub/foo.qute.html -> /foo` works just fine but `/pub/index.qute.html -> /` does not (and is fixed with this PR).

**Comment by mkouba** [comment]
We should probably also update the docs: https://github.com/quarkiverse/quarkus-qute-web/blob/main/docs/modules/ROOT/pages/index.adoc?plain=1#L9.

**Comment by kucharzyk** [comment]
You have right. 

The problem was only for index.qute.html
I thought it wasn’t working at all but when I stared fixing it I’ve realized it is only the case with index.qute.htm

I will update the docs later today

**Comment by kucharzyk** [comment]
@mkouba I've mentioned that we can use `index.qute.html` in docs.

There is one more thing that could be fixed later.

Currently `index.html` is available under paths `/`, `/index` and `/index.html`
But `index.qute.html` it is available under `/`, `/index' and '/index.qute.html` 

It's a bit inconsistent and I am not sure if it is intended behaviour.

**Comment by mkouba** [comment]
> @mkouba I've mentioned that we can use `index.qute.html` in docs.
> 
> There is one more thing that could be fixed later.
> 
> Currently `index.html` is available under paths `/`, `/index` and `/index.html` But `index.qute.html` it is available under `/`, `/index' and '/index.qute.html`
> 
> It's a bit inconsistent and I am not sure if it is intended behaviour.

@kucharzyk Hm, I don't think it's inconsistent. The idea is that you either use the _full_ template name (`/index.qute.html`) or the name without suffix (`/index`) so that an appropriate variant can be selected (based on the accept HTTP header). 

But it seems that we don't have a test for this use case. We should definitely add one.

I'd like to merge the fix for the index page first. Would you care to revert the other fix?

**Comment by kucharzyk** [comment]
Thank you for the feedback.
I will revert the other fix later today.

**Comment by mkouba** [comment]
> Thank you for the feedback. I will revert the other fix later today.

Thanks!

**Comment by kucharzyk** [comment]
@mkouba Done. I've reverted second fix

**Pull request merged**
