### PR TITLE
Allow asciidoc diagram block pre rendering using kroki.

### PR DESCRIPTION
**Pull request by jtama**
Links #142

### CODE REVIEW

**Review by ia3andy — COMMENTED** [review]
I am in PTO for 2 weeks, I won't be able to review this.

At first glance it seems it should be a separate extension as it brings other dependencies..

**Comment by mkouba** [comment]
> I am in PTO for 2 weeks, I won't be able to review this.
> 
> At first glance it seems it should be a separate extension as it brings other dependencies..

:+1: Also I wonder if it's practical/efficient to call an external service to render a diagram. Does asciidoctorj support this feature? If so we should probably rather work on https://github.com/quarkiverse/quarkus-qute-web/issues/119 :shrug:.

**Comment by jtama** [comment]
asciidoctorj alone doesn't handle diagram, but there is an asciidoctorj-diagram repository but I am not sure exactly sure what kind of diagram it handles.

Another point would be again not sure how it works, where would the rendered image be generated.

I can take a look if you want. Can you juste remember me, why asciidoctor-j was not chosen in the first place ?

**Comment by ia3andy** [comment]
> I took the kroki path, because this is the one Antora or Asciidoctor.js also took.
> 
> asciidoctorj alone doesn't handle diagram, but there is an asciidoctorj-diagram repository but I am not sure exactly sure what kind of diagram it handles.
> 
> Another point would be again not sure how it works, where would the rendered image be generated.
> 
> I can take a look if you want. Can you juste remember me, why asciidoctor-j was not chosen in the first place ?

Because we preferred having a light pure Java for the default even if it doesn't do everything, and because we can propose another extension for a heavier alternative for those who need it.

**Comment by jtama** [comment]
ok, so I have something else that could do the job, tested and working with roq with asciidoctorj and asciidoctorj-diagram.

Haven't even tried native though... Will make a PR tomorrow

**Pull request closed without merging**
